name: "ReportManager"
version: "1.0"
author: "xxAROX"
website: "https://github.com/HQGames/"
description: "ReportManager for HQGames by xxAROX."

api:
  - "4.0.0"
main: HQGames\plugin_name\plugin_name
